import React, { useState } from 'react';
import { MessageSquare, X, Send, Loader2, Bot, ChevronDown, RefreshCw } from 'lucide-react';

interface Message {
  role: 'user' | 'assistant';
  content: string;
  timestamp: Date;
}

interface SmartCopilotProps {
  onClose: () => void;
  onNavigate: (tab: string, payload?: any) => void;
}

const QUICK_PROMPTS = [
  'How do I generate a new appointment letter?',
  'How does DSC digital signing work?',
  'What is QR-based verification?',
  'How does bulk document generation work?',
  'Explain the approval workflow process',
  'What data is stored in the audit trail?',
];

function getReply(message: string): string {
  const m = message.toLowerCase();

  if (m.includes('generate') || m.includes('appointment') || m.includes('letter') || m.includes('wizard')) {
    return `To generate a new document:\n\n1. Navigate to **Generate Document** in the sidebar\n2. Select a template (Appointment Letter, Contractor Offer, etc.)\n3. Choose an employee/contractor from People Master\n4. Review and customize the auto-filled data\n5. Click **Generate** — the system creates a signed PDF with SHA-256 hash\n\nThe document is automatically added to the Approval Workflow queue for authorized signatory review.`;
  }
  if (m.includes('dsc') || m.includes('digital sign') || m.includes('hardware') || m.includes('token')) {
    return `**DSC (Digital Signature Certificate) Signing:**\n\nSmartDoc Sign supports three signing modes:\n\n- **Demo Mode** — Simulates the full signing workflow for UAT and demonstrations\n- **DSC Hardware Token** — USB Class 2/3 token integration (ePass 2003, Safenet iKey)\n- **eSign via Aadhaar OTP** — NSDL/CDAC-compliant cloud signing\n\nAll signatures embed timestamp, signer identity, IP address, and a SHA-256 document fingerprint into the tamper-proof sealed PDF.`;
  }
  if (m.includes('qr') || m.includes('verif')) {
    return `**QR-Based Document Verification:**\n\nEvery document generated by SmartDoc Sign includes an embedded QR code. Scanning it opens the **Verification Portal** which:\n\n1. Decodes the document UUID and generation hash\n2. Compares the stored SHA-256 hash against the file\n3. Displays complete signature metadata, timestamp, and signing chain\n4. Shows any tampering indicators in real-time\n\nThis enables instant offline-to-online verification for third parties such as banks, universities, or legal authorities.`;
  }
  if (m.includes('bulk')) {
    return `**Bulk Document Generation:**\n\nYou can generate documents for multiple employees simultaneously:\n\n1. Go to **Bulk Generation** in the sidebar\n2. Select a document template\n3. Upload a CSV file with employee data fields, or select from People Master\n4. Preview the first document to validate the template\n5. Click **Generate All** — the system queues all documents, generates PDFs, and sends notifications\n\nIdeal for joining batch letters, policy acknowledgement rollouts, or bonus circulars.`;
  }
  if (m.includes('approval') || m.includes('workflow')) {
    return `**Approval Workflow:**\n\nDocuments follow a configurable multi-level approval chain:\n\n1. **HR Admin** generates and initiates the document\n2. **Department Manager** reviews and either approves or requests changes\n3. **Authorized Signatory** provides the DSC digital signature\n4. **Employee** receives a notification and can acknowledge/download\n\nEach action is logged with user identity, IP, device, and timestamp in the immutable audit trail.`;
  }
  if (m.includes('audit') || m.includes('trail') || m.includes('log')) {
    return `**Audit Trail:**\n\nEvery platform event is logged immutably with:\n\n- Timestamp (ISO 8601 with timezone)\n- User identity and role\n- IP address and device fingerprint\n- Action category (Document, Signature, Access, Security)\n- SHA-256 hash snapshot of the document state at that moment\n\nThe audit trail is tamper-evident — any modification attempt is recorded and flagged. It is exportable as CSV or PDF for compliance and legal proceedings.`;
  }
  return `I can help you with:\n\n- Generating and managing employee or contractor documents\n- Understanding DSC / e-Sign digital signature workflows\n- Configuring approval chains and notifications\n- Navigating the Document Vault and Verification Portal\n- Interpreting the immutable audit trail\n- Bulk document generation and template versioning\n\nWhat would you like to know?`;
}

export const SmartCopilot: React.FC<SmartCopilotProps> = ({ onClose, onNavigate }) => {
  const [messages, setMessages] = useState<Message[]>([
    {
      role: 'assistant',
      content: 'Welcome to SmartDoc Sign Copilot. I can assist with document workflows, digital signature processes, template configuration, and compliance. How can I help you today?',
      timestamp: new Date(),
    },
  ]);
  const [input, setInput] = useState('');
  const [loading, setLoading] = useState(false);

  const send = async (text?: string) => {
    const msg = text || input.trim();
    if (!msg) return;
    setInput('');
    const userMsg: Message = { role: 'user', content: msg, timestamp: new Date() };
    setMessages(prev => [...prev, userMsg]);
    setLoading(true);
    await new Promise(r => setTimeout(r, 600));
    const reply = getReply(msg);
    setMessages(prev => [...prev, { role: 'assistant', content: reply, timestamp: new Date() }]);
    setLoading(false);
  };

  const formatContent = (text: string) => {
    const lines = text.split('\n');
    return lines.map((line, i) => {
      if (line.startsWith('**') && line.endsWith('**')) {
        return <div key={i} className="font-bold text-slate-900 mt-2 first:mt-0">{line.slice(2, -2)}</div>;
      }
      if (line.startsWith('- ')) {
        const content = line.slice(2).replace(/\*\*(.*?)\*\*/g, (_, t) => `<strong>${t}</strong>`);
        return <div key={i} className="flex gap-2 mt-1"><span className="text-sky-500 mt-0.5 shrink-0">-</span><span dangerouslySetInnerHTML={{ __html: content }} /></div>;
      }
      if (/^\d+\./.test(line)) {
        const content = line.replace(/\*\*(.*?)\*\*/g, (_, t) => `<strong>${t}</strong>`);
        return <div key={i} className="mt-1" dangerouslySetInnerHTML={{ __html: content }} />;
      }
      if (line === '') return <div key={i} className="mt-1" />;
      const content = line.replace(/\*\*(.*?)\*\*/g, (_, t) => `<strong>${t}</strong>`);
      return <div key={i} dangerouslySetInnerHTML={{ __html: content }} />;
    });
  };

  return (
    <div className="fixed bottom-0 right-0 w-[420px] h-[620px] bg-white rounded-tl-2xl shadow-2xl border border-slate-200 flex flex-col z-50 animate-slide-right"
      style={{ boxShadow: '-8px 0 40px rgba(0,0,0,0.12), 0 -8px 40px rgba(0,0,0,0.08)' }}>

      {/* Header */}
      <div className="flex items-center justify-between px-5 py-4 border-b border-slate-100 bg-gradient-to-r from-slate-900 to-slate-800 rounded-tl-2xl">
        <div className="flex items-center gap-3">
          <div className="w-8 h-8 rounded-lg bg-sky-500/20 border border-sky-400/30 flex items-center justify-center">
            <Bot size={16} className="text-sky-400" />
          </div>
          <div>
            <div className="text-[13px] font-bold text-white">Smart Copilot</div>
            <div className="text-[10px] text-emerald-400 font-semibold flex items-center gap-1">
              <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 inline-block animate-pulse" />
              Online
            </div>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={() => setMessages([messages[0]])}
            className="w-7 h-7 flex items-center justify-center rounded-md text-slate-400 hover:text-slate-200 hover:bg-slate-700 transition-colors"
            title="Clear conversation"
          >
            <RefreshCw size={14} />
          </button>
          <button
            onClick={onClose}
            className="w-7 h-7 flex items-center justify-center rounded-md text-slate-400 hover:text-slate-200 hover:bg-slate-700 transition-colors"
          >
            <X size={16} />
          </button>
        </div>
      </div>

      {/* Messages */}
      <div className="flex-1 overflow-y-auto px-4 py-4 space-y-4">
        {messages.map((m, i) => (
          <div key={i} className={`flex ${m.role === 'user' ? 'justify-end' : 'justify-start'}`}>
            <div className={`max-w-[90%] rounded-xl px-4 py-3 text-[12.5px] leading-relaxed ${
              m.role === 'user'
                ? 'bg-sky-600 text-white rounded-br-sm'
                : 'bg-slate-50 border border-slate-200 text-slate-700 rounded-bl-sm'
            }`}>
              {m.role === 'assistant' ? formatContent(m.content) : m.content}
              <div className={`text-[10px] mt-1.5 ${m.role === 'user' ? 'text-sky-200' : 'text-slate-400'}`}>
                {m.timestamp.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
              </div>
            </div>
          </div>
        ))}
        {loading && (
          <div className="flex justify-start">
            <div className="bg-slate-50 border border-slate-200 rounded-xl px-4 py-3 flex items-center gap-2 text-[12px] text-slate-500">
              <Loader2 size={13} className="animate-spin text-sky-500" />
              Thinking...
            </div>
          </div>
        )}
      </div>

      {/* Quick Prompts */}
      <div className="px-4 pb-2">
        <div className="flex gap-2 overflow-x-auto pb-1 scrollbar-hide">
          {QUICK_PROMPTS.map(p => (
            <button
              key={p}
              onClick={() => send(p)}
              className="shrink-0 px-2.5 py-1 rounded-full border border-slate-200 text-[11px] font-medium text-slate-600 hover:bg-sky-50 hover:border-sky-300 hover:text-sky-700 transition-colors whitespace-nowrap"
            >
              {p}
            </button>
          ))}
        </div>
      </div>

      {/* Input */}
      <div className="px-4 pb-4">
        <div className="flex items-end gap-2 bg-slate-50 border border-slate-200 rounded-xl p-2 focus-within:border-sky-400 focus-within:ring-2 focus-within:ring-sky-100 transition-all">
          <textarea
            value={input}
            onChange={e => setInput(e.target.value)}
            onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); send(); } }}
            placeholder="Ask about workflows, signatures, templates..."
            rows={1}
            className="flex-1 bg-transparent text-[12.5px] text-slate-800 placeholder:text-slate-400 focus:outline-none resize-none leading-relaxed max-h-24 overflow-y-auto"
          />
          <button
            onClick={() => send()}
            disabled={!input.trim() || loading}
            className="w-8 h-8 rounded-lg flex items-center justify-center text-white bg-sky-600 hover:bg-sky-700 disabled:opacity-40 disabled:cursor-not-allowed transition-all active:scale-95 shrink-0"
          >
            <Send size={14} />
          </button>
        </div>
        <p className="text-[10px] text-slate-400 text-center mt-2">
          Press Enter to send · Shift+Enter for new line
        </p>
      </div>

    </div>
  );
};
